### ISSUE TITLE
Does first dimension has a limit of 12?

### ISSUE THREAD

**Issue by vissu430** [SirGarnet/qlik-sense-timeline#3]
Hello,

This visualization works great but it is limiting my first dimension values to 12 only. Wondering if this is by design or is there a place to tweak this setting to increase the limit.

**Comment by SirGarnet** [comment]
Hi vissu430,

google gives no information abaut the dimension limitation. But i think your limitation is a problem of Qlik Sense, that I will fix in the future.

The reason is, that Qlik Sense only transfers 10,000 fields to a visualisation in the initial call. That means if you use all 2 dimensions and 3 meassures for the visualisation. Qlik only provides 10,000 fields. These fields are transfered in a table with 5 columns (2 dim + 3 mess). If you devide 10,000 fields by 5 columns the initial data is limited to 2,000 rows.

I'm aware of this problem and will take a look in the future release.

**Comment by vissu430** [comment]
SirGarnet,

Thank you for the fast response.

I only have 2 dimensions (vehicle, tripID) and 2 measures (start date time, end date time) with total 1700 rows of data from 50 unique vehicles. Based on your explanation, my understanding is 10,000 fields by 5 columns should be able to support at least 2500 rows but I can only see 12 vehicles in my visualization.

Please let me know if I am not clear about my explanation.

Thanks,
Srini

**Comment by SirGarnet** [comment]
Hi Srini,

don't panic, I removed some confidential data from you last post.

Can you give me a short description of your used data, so i can rebuild it on my side.

So far I know:
- 50 unique vehicleIDs
- unknown count of tripIDs incl. Start- & End-Time

Known relations:
- vehicleID 1 --> N tripID
- tripID 1 --> 1 vehicleID

How many tripIDs do you have in min / avg / max per vehicleID and the sum of tripIDs.

How are your tables structured?

Greetings SirGarnet

**Comment by vissu430** [comment]
Please find the table structure below.

TripID   VehicleID   start_time                                 end_time
1000      Vehicle1    2019-01-01 07:10:03 AM         2019-01-01 07:30:03 AM

There are about 1700 trips from 50 vehicles (vehicle1, vehicle2.......vehicle50) like this in our sample data where visualization is showing only 12 vehicles since it was selected as a primary dimension.

**Comment by vissu430** [comment]
Also, there are about 40 trips per vehicle.

**Comment by SirGarnet** [comment]
Hi Srinivas,

I have a solution for your request. I will upload a new version tomorrow - for me it is 01:00 AM so time to sleep. There are some options that I want to add for EditMode and for row limitation. Stay tuned.

Greetings SirGarnet

**Comment by vissu430** [comment]
Great, really appreciate your commitment.

**Comment by vissu430** [comment]
Awesome!!!
Works great, thank you!!!
